[package]
name = "asm"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = 'abort'

[profile.dev]
opt-level = 0               # Use slightly better optimizations.
overflow-checks = false

[dependencies]
