[package]
name = "asm"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = 'abort'

[profile.dev]
opt-level = 0
overflow-checks = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(st32f4xx)', 'cfg(st32f7xx)'] }
